class CreateProducts < ActiveRecord::Migration[8.0]
  def change
    create_table :products do |t|
      t.string :code
      t.string :url
      t.string :creator
      t.integer :created_t
      t.datetime :created_datetime
      t.integer :last_modified_t
      t.datetime :last_modified_datetime
      t.string :product_name
      t.string :generic_name
      t.string :quantity

      # Tags
      t.text :packaging
      t.text :packaging_tags
      t.string :brands
      t.text :brands_tags
      t.text :categories
      t.text :categories_tags
      t.text :categories_fr
      t.text :origins
      t.text :origins_tags
      t.text :manufacturing_places
      t.text :manufacturing_places_tags
      t.text :labels
      t.text :labels_tags
      t.text :labels_fr
      t.text :emb_codes
      t.text :emb_codes_tags
      t.string :first_packaging_code_geo
      t.text :cities
      t.text :cities_tags
      t.text :purchase_places
      t.text :stores
      t.text :countries
      t.text :countries_tags
      t.text :countries_fr

      # Ingredients
      t.text :ingredients_text
      t.text :traces
      t.text :traces_tags

      # Misc data
      t.string :serving_size
      t.boolean :no_nutriments
      t.integer :additives_n
      t.text :additives
      t.text :additives_tags
      t.integer :ingredients_from_palm_oil_n
      t.text :ingredients_from_palm_oil
      t.text :ingredients_from_palm_oil_tags
      t.integer :ingredients_that_may_be_from_palm_oil_n
      t.text :ingredients_that_may_be_from_palm_oil
      t.text :ingredients_that_may_be_from_palm_oil_tags
      t.string :nutrition_grade_fr
      t.string :main_category
      t.string :main_category_fr
      t.string :image_url
      t.string :image_small_url

      # Nutrition facts (decimal for precision)
      t.float :energy_100g
      t.float :energy_kj_100g
      t.float :energy_kcal_100g
      t.float :proteins_100g
      t.float :casein_100g
      t.float :serum_proteins_100g
      t.float :nucleotides_100g
      t.float :carbohydrates_100g
      t.float :sugars_100g
      t.float :sucrose_100g
      t.float :glucose_100g
      t.float :fructose_100g
      t.float :lactose_100g
      t.float :maltose_100g
      t.float :maltodextrins_100g
      t.float :starch_100g
      t.float :polyols_100g
      t.float :fat_100g
      t.float :saturated_fat_100g
      t.float :butyric_acid_100g
      t.float :caproic_acid_100g
      t.float :caprylic_acid_100g
      t.float :capric_acid_100g
      t.float :lauric_acid_100g
      t.float :myristic_acid_100g
      t.float :palmitic_acid_100g
      t.float :stearic_acid_100g
      t.float :arachidic_acid_100g
      t.float :behenic_acid_100g
      t.float :lignoceric_acid_100g
      t.float :cerotic_acid_100g
      t.float :montanic_acid_100g
      t.float :melissic_acid_100g
      t.float :monounsaturated_fat_100g
      t.float :polyunsaturated_fat_100g
      t.float :omega_3_fat_100g
      t.float :alpha_linolenic_acid_100g
      t.float :eicosapentaenoic_acid_100g
      t.float :docosahexaenoic_acid_100g
      t.float :omega_6_fat_100g
      t.float :linoleic_acid_100g
      t.float :arachidonic_acid_100g
      t.float :gamma_linolenic_acid_100g
      t.float :dihomo_gamma_linolenic_acid_100g
      t.float :omega_9_fat_100g
      t.float :oleic_acid_100g
      t.float :elaidic_acid_100g
      t.float :gondoic_acid_100g
      t.float :mead_acid_100g
      t.float :erucic_acid_100g
      t.float :nervonic_acid_100g
      t.float :trans_fat_100g
      t.float :cholesterol_100g
      t.float :fiber_100g
      t.float :sodium_100g
      t.float :alcohol_100g
      t.float :vitamin_a_100g
      t.float :vitamin_d_100g
      t.float :vitamin_e_100g
      t.float :vitamin_k_100g
      t.float :vitamin_c_100g
      t.float :vitamin_b1_100g
      t.float :vitamin_b2_100g
      t.float :vitamin_pp_100g
      t.float :vitamin_b6_100g
      t.float :vitamin_b9_100g
      t.float :vitamin_b12_100g
      t.float :biotin_100g
      t.float :pantothenic_acid_100g
      t.float :silica_100g
      t.float :bicarbonate_100g
      t.float :potassium_100g
      t.float :chloride_100g
      t.float :calcium_100g
      t.float :phosphorus_100g
      t.float :iron_100g
      t.float :magnesium_100g
      t.float :zinc_100g
      t.float :copper_100g
      t.float :manganese_100g
      t.float :fluoride_100g
      t.float :selenium_100g
      t.float :chromium_100g
      t.float :molybdenum_100g
      t.float :iodine_100g
      t.float :caffeine_100g
      t.float :taurine_100g
      t.float :ph_100g
      t.float :fruits_vegetables_nuts_100g
      t.float :carbon_footprint_100g
      t.integer :nutrition_score_fr_100g
      t.integer :nutrition_score_uk_100g

      t.timestamps
    end
    add_index :products, :code, unique: true
  end
end
